include ../../make.inc

all:
#	$(CC) $(CFLAGS) $(INCLUDES) stockdb_test.cc
#	$(CC) $(CFLAGS) $(INCLUDES) mean.cc
#	$(CC) $(CFLAGS) $(INCLUDES) variance.cc
#	$(CC) $(CFLAGS) $(INCLUDES) autocovariance.cc
#	$(CC) $(CFLAGS) $(INCLUDES) autocorrelation.cc
#	$(CC) $(CFLAGS) $(INCLUDES) covariance.cc
#	$(CC) $(CFLAGS) $(INCLUDES) correlation.cc
#	$(CC) $(CFLAGS) $(INCLUDES) autocorrelation_function.cc
#	$(CC) $(CFLAGS) $(INCLUDES) partial_autocorrelation_function.cc

exe:
#	$(CC) $(INCLUDES) $(LIBDIRS) ./mean.o ../statistics/statistics.o -o ../../testing/mean $(LIBS_LAPACK)
#	$(CC) $(INCLUDES) $(LIBDIRS) ./variance.o ../statistics/statistics.o -o ../../testing/variance $(LIBS_LAPACK)
#	$(CC) $(INCLUDES) $(LIBDIRS) ./autocovariance.o ../statistics/statistics.o -o ../../testing/autocovariance $(LIBS_LAPACK)
#	$(CC) $(INCLUDES) $(LIBDIRS) ./autocorrelation.o ../statistics/statistics.o -o ../../testing/autocorrelation $(LIBS_LAPACK)
#	$(CC) $(INCLUDES) $(LIBDIRS) ./covariance.o ../statistics/statistics.o -o ../../testing/covariance $(LIBS_LAPACK)
#	$(CC) $(INCLUDES) $(LIBDIRS) ./correlation.o ../statistics/statistics.o -o ../../testing/correlation $(LIBS_LAPACK)
#	$(CC) $(INCLUDES) $(LIBDIRS) ./autocorrelation_function.o ../statistics/statistics.o -o ../../testing/autocorrelation_function $(LIBS_LAPACK)
#	$(CC) $(INCLUDES) $(LIBDIRS) ./partial_autocorrelation_function.o ../statistics/statistics.o -o ../../testing/partial_autocorrelation_function $(LIBS_LAPACK)
#	$(CC) $(INCLUDES) ./stockdb_test.o ../database/StockDBConnection.o -o ../../testing/stockdb_test -lmysqlclient

clean:
	rm -f *.o
